### PR TITLE
Make the bot work more reliable, advanced logging, fish / fishing line throw counters

### PR DESCRIPTION
**Pull request by cyb3rko**
Hey there,
I found the fishington.io game and I wondered if I could develop a bot for it, but we found your bot so I tried to improve yours.

I tried it out and it didn't work for me because the trigger values for the template matching were too high, so I adjusted them to work for me and a friend of mine. Please try it out and see it it also works for you.

Here are all the other changes:
- improved logging to make the current steps more clear to the users and to include opencv values for the template matching for better error solving (if something does not work for you)
- added counters for how many fish you have caught all in all and how often you have thrown your fishing line.
- the bot waits for 5 seconds now until it starts (so you have more time to go to fishington after starting the bot)
- the bot waits until there's the exclamation mark above your head so it does not pull in the line before a fish is hooked (makes it way more efficient)
- increase minimum throw time to 0.4 instead of 0.2 to prevent failing throw attempts
- some smaller fixes and code formatting

Happy to hear from you :)

### CODE REVIEW

**Comment by bahadiraraz** [comment]
> Hey there, I found the fishington.io game and I wondered if I could develop a bot for it, but we found your bot so I tried to improve yours.
> 
> I tried it out and it didn't work for me because the trigger values for the template matching were too high, so I adjusted them to work for me and a friend of mine. Please try it out and see it it also works for you.
> 
> Furthermore I improved the logging to make the current steps more clear to the users and to include opencv values for the template matching for better error solving (if something does not work for you).
> 
> Another thing I added are counters for how many fish you have caught all in all and how often you have thrown your fishing line.
> 
> Happy to hear from you :)

I will review it when available, I'm a little busy these days.

**Comment by cyb3rko** [comment]
I have included some more fixes and new features.
Should I just add them here to the same pull request or just wait until it's merged and open a new one?

**Comment by bahadiraraz** [comment]
> I have included some more fixes and new features. Should I just add them here to the same pull request or just wait until it's merged and open a new one?

you can add here

**Comment by cyb3rko** [comment]
Here we go, that's it.

**Comment by cyb3rko** [comment]
I updated the pull request message to contain all the changes I've made.

**Comment by cyb3rko** [comment]
And last but not least I've made some measurements and calculations, it seems that the new improvements have made the bot around 30% faster than the first version of this bot.

64,36 <=> 83,25 fish / hour

**Pull request merged**
